name: Lighthouse CI
on: pull_request
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@main
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 480
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        env:
          ENVIRONMENT_URL: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
        with:
          urls: |
            $ENVIRONMENT_URL/
            $ENVIRONMENT_URL/resume
            $ENVIRONMENT_URL/blog
            $ENVIRONMENT_URL/blog/adding-themed-color-classes-to-bootstrap
            $ENVIRONMENT_URL/blog/launch-angular-from-vs-project
            $ENVIRONMENT_URL/blog/mdx-custom-fenced-codeblocks
          runs: 3
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
